[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
messenger = "CeJMhcoHmBUKuKVVL34qU7UCVe8QH1KTFUMivCANTEbA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/hoooooou_jun/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
